In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
DATA_DIR = PROJECT_ROOT / 'data'

df = pd.read_csv(DATA_DIR / 'tax_fraud_dataset_cleaned.csv')

df.head()

,Taxpayer_ID,Business_Type,Region,Years_in_Business,Employee_Count,Annual_Revenue,Annual_Expenses,Net_Profit,Taxable_Income,Expected_Tax,...,Late_Payments,Industry_Risk,Cash_Transactions_Percentage,Missing_Documents,Invoice_Mismatch,Expense_Ratio,Profit_Margin,Revenue_per_Employee,Tax_Gap,Fraud
0,100000,Restaurant,Cairo,10,9,1892448.36,839511.26,1052937.10,919634.40,206917.74,...,0,Medium,58.87,0,0,0.444,0.556,210272.04,5987.61,0
1,100001,Pharmacy,Giza,0,17,2129742.33,923661.40,1206080.92,1078021.30,242554.79,...,1,Low,5.98,0,0,0.434,0.566,125278.96,7992.36,0
2,100002,Restaurant,Sharqia,4,8,789223.93,334017.67,455206.26,420736.46,94665.70,...,0,Medium,69.98,4,1,0.423,0.577,98652.99,13609.28,1
3,100003,Manufacturing,Cairo,7,8,427211.55,361951.79,65259.77,58963.05,13266.69,...,0,Medium,42.56,1,0,0.847,0.153,53401.44,450.54,0
4,100004,Import/Export,Sharqia,3,8,1516452.68,831833.16,684619.52,588453.59,132402.06,...,2,High,39.09,1,0,0.549,0.451,189556.58,1436.03,0

In [13]:
df_tax_gap = df[(df['Tax_Gap']>30000) & (df['Fraud'] == 0)]

print(len(df_tax_gap))
df_tax_gap.head()

110

,Taxpayer_ID,Business_Type,Region,Years_in_Business,Employee_Count,Annual_Revenue,Annual_Expenses,Net_Profit,Taxable_Income,Expected_Tax,...,Late_Payments,Industry_Risk,Cash_Transactions_Percentage,Missing_Documents,Invoice_Mismatch,Expense_Ratio,Profit_Margin,Revenue_per_Employee,Tax_Gap,Fraud
195,100195,Import/Export,Cairo,10,5,6505598.51,2740323.71,3765274.80,3754299.91,844717.48,...,0,High,54.33,0,0,0.421,0.579,1301119.70,34922.85,0
447,100447,Restaurant,Dakahlia,7,27,6792205.47,3794547.49,2997657.98,2782060.66,625963.65,...,1,Medium,9.45,1,1,0.559,0.441,251563.17,37727.54,0
581,100581,Manufacturing,Monufia,6,17,2915666.07,1097407.10,1818258.97,1773691.75,399080.64,...,1,Medium,58.31,1,0,0.376,0.624,171509.77,31529.21,0
861,100861,IT,Monufia,7,8,8542923.72,3020436.95,5522486.77,4872629.10,1096341.55,...,0,Low,56.96,1,0,0.354,0.646,1067865.47,43118.84,0
1155,101155,IT,Giza,4,10,3339121.48,1331363.68,2007757.80,1974551.19,444274.02,...,0,Low,32.59,0,0,0.399,0.601,333912.15,33164.64,0

In [17]:
df_tax_gap = df[(df['Tax_Gap']==0) & (df['Fraud'] == 1)]

print(len(df_tax_gap))
df_tax_gap.head()

270

,Taxpayer_ID,Business_Type,Region,Years_in_Business,Employee_Count,Annual_Revenue,Annual_Expenses,Net_Profit,Taxable_Income,Expected_Tax,...,Late_Payments,Industry_Risk,Cash_Transactions_Percentage,Missing_Documents,Invoice_Mismatch,Expense_Ratio,Profit_Margin,Revenue_per_Employee,Tax_Gap,Fraud
208,100208,Import/Export,Alex,10,13,738884.58,418419.04,320465.55,304663.59,68549.31,...,1,High,34.35,0,0,0.566,0.434,56837.28,0.0,1
383,100383,Pharmacy,Monufia,11,20,1323410.47,844443.03,478967.44,433935.45,97635.48,...,1,Low,77.95,0,0,0.638,0.362,66170.52,0.0,1
465,100465,Education,Giza,9,13,604630.62,432714.29,171916.33,162724.45,36613.00,...,1,Low,19.81,1,0,0.716,0.284,46510.05,0.0,1
497,100497,Retail,Sharqia,6,20,1090123.86,602121.90,488001.96,467354.86,105154.84,...,1,Medium,24.57,1,0,0.552,0.448,54506.19,0.0,1
922,100922,Construction,Monufia,0,7,1121653.53,923034.56,198618.97,190136.41,42780.69,...,1,High,29.28,1,0,0.823,0.177,160236.22,0.0,1

In [16]:
df_employee_count = df[(df['Employee_Count']<2) & (df['Fraud'] == 1)]
print(len(df_employee_count))
df_employee_count.head()

11

,Taxpayer_ID,Business_Type,Region,Years_in_Business,Employee_Count,Annual_Revenue,Annual_Expenses,Net_Profit,Taxable_Income,Expected_Tax,...,Late_Payments,Industry_Risk,Cash_Transactions_Percentage,Missing_Documents,Invoice_Mismatch,Expense_Ratio,Profit_Margin,Revenue_per_Employee,Tax_Gap,Fraud
1823,101823,Retail,Cairo,0,1,1961013.10,780427.55,1180585.55,1015074.58,228391.78,...,2,Medium,84.85,1,0,0.398,0.602,1961013.10,15043.76,1
12054,112054,Healthcare,Alex,14,1,4619544.88,2452527.34,2167017.54,2059165.81,463312.31,...,1,Low,74.65,1,0,0.531,0.469,4619544.88,100773.79,1
17648,117648,Restaurant,Giza,6,1,4988452.73,2727793.49,2260659.24,1981869.47,445920.63,...,0,Medium,26.87,1,0,0.547,0.453,4988452.73,56542.44,1
24390,124390,Import/Export,Alex,14,1,373027.75,233122.49,139905.26,133897.17,30126.86,...,2,High,67.37,1,0,0.625,0.375,373027.75,0.00,1
26927,126927,Construction,Giza,12,1,2689146.51,2203160.96,485985.55,421472.08,94831.22,...,3,High,26.17,0,0,0.819,0.181,2689146.51,17456.40,1